name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/metaboigniter') }}"
    runs-on: ubuntu-latest
<<<<<<< HEAD
    env:
      NXF_VER: "20.04.0" #${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
=======
>>>>>>> 74c6005ac02d52f02a82b3b1f1c02fd3318047b8
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
<<<<<<< HEAD
        uses: actions/checkout@v2

      - name: Check if Dockerfile or Conda environment changed
        uses: technote-space/get-diff-action@v4
        with:
          FILES: |
            Dockerfile

      - name: Build new docker image
        if: env.MATCHED_FILES
        run: docker build --no-cache . -t nfcore/metaboigniter:dev

      - name: Pull docker image
        if: ${{ !env.MATCHED_FILES }}
        run: |
          docker pull nfcore/metaboigniter:dev
          docker tag nfcore/metaboigniter:dev nfcore/metaboigniter:dev
=======
        uses: actions/checkout@v3
>>>>>>> 74c6005ac02d52f02a82b3b1f1c02fd3318047b8

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --outdir ./results
